#!/bin/bash

GH_REMOTE=origin

if [[ -z "$1" ]]; then
    GH_PAGESBRANCH=gh-pages
else
    GH_PAGESBRANCH="$1"
fi

echo "*********************************************************************"
echo "WARNING! This script will remove the local branch '$GH_PAGESBRANCH',"
echo "build the notebook files into HTML, then push to remote gh-pages"
echo "located here: $GH_REMOTE/$GH_PAGESBRANCH."
echo
echo "Make sure you have no uncommitted changes in your master branch"
echo "as these may be overwritten!"
echo
read -p "Are you sure you want to do this? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # first run the notebooks
    OUTPUT=`python prepare_deploy.py run`
    if [[ $OUTPUT == *ERROR* ]]
    then
        echo "Error running notebook files!";
        exit;
    fi

    # then convert the notebooks to HTML
    OUTPUT=`python prepare_deploy.py convert`
    if [[ $OUTPUT == *ERROR* ]]
    then
        echo "Error converting notebook files to HTML!";
        exit;
    fi

    # remove the old gh-pages branch
    OUTPUT=`git branch -D gh-pages`
    if [[ $OUTPUT == *fatal* ]]
    then
        echo "Error deleting gh-pages branch.";
        exit;
    fi

    # Create a new "orphaned" branch -- we don't need history for
    # the built products
    git checkout --orphan $GH_PAGESBRANCH

    # Copy the built files to a tmp location
    cp -R html _tmp

    # This will delete all of the git-managed files here
    git rm -rf .

    # Now copy the html back into here
    cp -R _tmp/* .
    rm -rf _tmp

    git add *.html
    git add images
    git add css
    git commit -m "Generated from sources"

    read -p "Would you like to preview the rendered HTML? [y/N] " -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "\n\n"
        open index.html
    else
        echo "\n"
    fi

    read -p "Are you sure you want to push to live gh-pages? [y/N] " -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "\n"
        echo "Pushing to gh-pages branch"
        git push -f $GH_REMOTE $GH_PAGESBRANCH

        git checkout -f master
        git clean -f
        git branch -D gh-pages
    else
        echo "\n"
        echo "You're now in an orphaned test deploy branch."
        echo "To get back to normal you can run the following:"
        echo "    git checkout -f master"
        echo "    git clean -f"
        echo "    git branch -D gh-pages"
    fi
fi
