#!/bin/bash

# The key element here is using ``travis encrypt GH_TOKEN=<github personal token>``
# and then adding the resulting secure key/value pair to .travis.yml

echo "Adding deployment remote"
git remote add deploy "https://${GH_TOKEN}@${GH_REF}"

export CURRENT_BRANCH_NAME="$(git rev-parse HEAD)"
export INTERACTIVE=false 
export GH_REMOTE=deploy
./deploy